categories:
  - title: "🚨 Features 🚨"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes 🐛"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "💥 Breaking Change 💥"
    labels:
      - "breaking-change"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## ✨ Changes ✨

  $CHANGES
