name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
categories:
  - title: ":boom: Breaking Change :boom:"
    labels:
      - "breaking-change"
  - title: ":zap: Enhancments :zap:"
    labels:
      - "enhancement"
      - "refactor"
  - title: ":sparkles: New Features :sparkles:"
    labels:
      - "feature"
  - title: ":bug: Bug Fixes :bug:"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: ":wrench: Maintenance :wrench:"
    labels:
      - "chore"
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/moralmunky/Home-Assistant-Mail-And-Packages/$RESOLVED_VERSION/total.svg)](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki)
  - [Submit bugs/feature requests](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues)
