blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/discussions
    about: Please ask and answer questions here.
