name: Validate with hassfest

on:
  push:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  formatting:
    runs-on: "ubuntu-latest"
    steps:
      - uses: fylein/python-pylint-github-action@v4
    
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"
        - uses: "home-assistant/actions/hassfest@master"

